//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opgave16_2_16_3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class linqDataBaseEntities : DbContext
    {
        public linqDataBaseEntities()
            : base("name=linqDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<car> cars { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<rentcustomer> rentcustomers { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
    }
}
